### ISSUE TITLE
Convertor: Remove breakage marking in FORM field 

### ISSUE THREAD

**Issue by epageperron** [cdli-gh/atf2conll-convertor#1]
_From @epageperron on December 2, 2017 18:6_

When converting from ATF to CDLI-Conll, clean up data in the FORM field, removing square bracket characters and the hash character [ ] #

_Copied from original issue: cdli-gh/morphology-pre-annotation-tool#6_

**Comment by epageperron** [comment]
_From @jayanthjaiswal on January 4, 2018 19:10_

[]#

**Comment by jayanthjaiswal** [comment]
@epageperron What should I do with the characters enclosed and surrounding the characters?

```
1(u)#
mu#
```

```
zi#-[ga]
[1(u) 5(disz) 2/3(disz) gin2]
[...] x
```
If I remove them and this gives empty token, should I keep them in conll with numbering or remove them like "[]"

**Comment by jayanthjaiswal** [comment]
Done. I am just removing them directly irrespective of the final output string.

**Comment by epageperron** [comment]
If you remove them before tokenizing it should work? We only need to remove the three characters, not what is in the brackets

**Comment by jayanthjaiswal** [comment]
I have done the same. I have not removed anything else. This issue should be closed.
