### ISSUE TITLE
< > in ATF not handled properly

### ISSUE THREAD

**Issue by epageperron** [cdli-gh/atf2conll-convertor#13]
<SIGN> in ATF should be converted to SIGN in Conll

Eg
in  P101276
r.4.1 `ku-da-<nu>-um` should be `ku-da-nu-um` when converted to conll

**Comment by epageperron** [comment]
( Thanks to @wangj619 for the report )

**Comment by jayanthjaiswal** [comment]
Only if they are in pairs.
If they are not in pairs, check in pyoracc.

**Comment by epageperron** [comment]
http://cdli.ucla.edu/P101276

**Comment by jayanthjaiswal** [comment]
@epageperron  @wangj619 The issue is not there is the recent version of tool. 
It was fixed here:
https://github.com/cdli-gh/atf2conll-convertor/commit/b83a26d09b042375d9a16cd6a2cbbf60909e4f0a#diff-44cab452904c316b52b6165f03aa5f52R111
