### ISSUE TITLE
($ xxx $) not handled properly

### ISSUE THREAD

**Issue by epageperron** [cdli-gh/atf2conll-convertor#14]
Any text between ($ $) should be fully ignored, including the boundaries markers,

see  P102339 : 

o.6.1 ($
o.6.2 blank
o.6.3 space
o.6.4 $)

cc: @wangj619

**Comment by jayanthjaiswal** [comment]
Anything in this should be removed. 
($ always in pair with $).
If not, add in pyoracc.

**Comment by epageperron** [comment]
https://cdli.ucla.edu/P102339  line 11
