### ISSUE TITLE
Convertor: Conversion from ATF to Conll should abbreviate surface name and add columns when present

### ISSUE THREAD

**Issue by epageperron** [cdli-gh/atf2conll-convertor#2]
_From @epageperron on November 21, 2017 5:24_

columns should be encoded as .col#. in the sequence and appear only when there are columns

_Copied from original issue: cdli-gh/morphology-pre-annotation-tool#5_

**Comment by jayanthjaiswal** [comment]
Done with https://github.com/cdli-gh/atf2conll-convertor/commit/34fff022e77a7fe915f752b874bdee97af7ee211
