### ISSUE TITLE
Convertor: Conversion from ATF to Conll should handle multiple texts

### ISSUE THREAD

**Issue by epageperron** [cdli-gh/atf2conll-convertor#3]
_From @epageperron on November 21, 2017 5:20_

When an ATF file contains more than one text, the converter should parse them as multiple texts and create an individual file for each.

_Copied from original issue: cdli-gh/morphology-pre-annotation-tool#4_

**Comment by jayanthjaiswal** [comment]
It is fixed now with https://github.com/cdli-gh/atf2conll-convertor/commit/5f5ec42d226953105104543ae66c33a2ece580e9.

**Comment by epageperron** [comment]
Fantastic !! We can now mass produce conll files and conquer the world :)
