### ISSUE TITLE
remove <> from form

### ISSUE THREAD

**Issue by epageperron** [cdli-gh/atf2conll-convertor#7]
_From @epageperron on January 15, 2018 21:27_

Before tokenizing/creating the form column, also remove  < and > just like the square brackets and hash are removed, also ! and ?

_Copied from original issue: cdli-gh/morphology-pre-annotation-tool#17_

**Comment by epageperron** [comment]
_From @jayanthjaiswal on January 15, 2018 21:33_

@epageperron should this be part of this tool or [atf2conll](https://github.com/cdli-gh/atf2conll-convertor)?

**Comment by epageperron** [comment]
yes ! will move the issue

**Comment by jayanthjaiswal** [comment]
@epageperron I have removed these characters till now:
[]#<>!?
Let me know, if I miss something.

**Comment by epageperron** [comment]
Perfect thanks !
