### ISSUE TITLE
IDs generated are not unique

### ISSUE THREAD

**Issue by khoidt** [cdli-gh/atf2conll-convertor#8]
While using the converter I stumbled upon multiple occurrences of the `IDs generated are not unique` error (see [not_unique.txt](https://github.com/cdli-gh/atf2conll-convertor/files/1896409/not_unique.txt)).

@jayanthjaiswal, do I understand right that it's an issue that has to do with incorrect ATF formatting / repeated line numbers?
@epageperron, can such texts be included in the gold corpus? If so, how should I treat them?

**Comment by epageperron** [comment]
Yes, I would need to correct the ATF, then we can pull those texts out and re-convert them. On my todo ! I'll add here problem which are not in the ATF but in the generation of IDs

**Comment by epageperron** [comment]
Jayanth the first atf is not parsed properly, sending you the files on Slack

**Comment by epageperron** [comment]
Ilya I think you didn't update the atf2conll tool !

**Comment by jayanthjaiswal** [comment]
@epageperron Please close this issue after testing again.

**Comment by khoidt** [comment]
@epageperron [atf2conll_errors.log](https://github.com/cdli-gh/atf2conll-convertor/files/1908254/atf2conll_errors.log) contains all error messages from the program's latest version applied to the whole MTAAC Ur III corpus.
